[git_branch]
symbol = ""

[battery]
disabled = true

[container]
disabled = true

[directory]
truncate_to_repo = false

[aws]
force_display = true

[gcloud]
detect_env_vars = ['CLOUDSDK_ACTIVE_CONFIG_NAME']
